name: OneBlock
version: 1.0.0
main: me.davidjawhar.oneblock.OneBlockPlugin
api-version: "1.21"
author: DavidJawhar
commands:
  ob:
    description: OneBlock commands
    usage: /ob <home|tp|info|reset|reload>
permissions:
  oneblock.use:
    default: true
  oneblock.home:
    default: true
  oneblock.tp:
    default: op
  oneblock.info:
    default: true
  oneblock.admin:
    default: op
